service: luxy

plugins:
  - serverless-finch

custom:
  stage: ${opt:stage, self:provider.stage}
  client:
    bucketName: ${self:service}-${self:custom.stage}-static
    distributionFolder: dist

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
